#!/usr/bin/env bash
#
# This main project script which configure/install my Debian environment.
# Configures the necessary tools for development and convenience.
# Minimalistic environment and instruments with old-school themes/fonts.
# Tested on Debian Bookworm and Trixie, but I currently use it on Trixie.
#
# --- (!!!) (!!!) (!!!) -------------------------- (!!!) (!!!) (!!!) ---
# Be careful when running this script on your main machine, it does not
# create backup dotfiles and may erase your current working environment.
# It's better to read the script before using it. It's simple.
# --- (!!!) (!!!) (!!!) -------------------------- (!!!) (!!!) (!!!) ---
#
# After running:
# $ ./init --xfce
# $ ./init --lightdm
# $ ./init --unclutter
# $ ./init --clean-home
# $ ./init --purge-packages
# $ ./init --set-korux-theme
# $ ./init --system-defaults
# $ ./init --telegram-desktop
# need to restart the session. You can use:
# $ sudo systemctl restart display-manager
#

set -ex

umask 077

check_package()
{
	dpkg -l | awk '{print $2}' | grep ^$1$ &>/dev/null && return 0 || return 1
}

# ----------------------------------------------------------------------

bold_message()
{
	echo -e "\e[96m*** ----- $1 ----- ***\e[0m"
}

usage()
{
cat << EOF
Usage: $(basename $0) [option]

  [option]

  --install-packages     install environment packages from pkgs.list

  --purge-packages       free the system from unnecessary packages

  --sources-list         sources.list installation (Trixie)

  --clean-home           remove default XDG dirs, apply user-dirs.*, enable init.d clean-home

  --bash                 ~/.bashrc and ~/.bash_aliases installation

  --dircolors            ~/.dircolors installation

  --bash-completion      enable bash completion

  --sudo                 add a $USER to the sudo group

  --locales              generate en_US/ru_RU locales and set 'en_US' as default

  --xfce                 full xfce installation (desktop session)
                         includes all ~/.config/xfce4/xfconf/xfce-perchannel-xml files

  --xfce-terminal        xfce terminal emulator installation
                         ~/.config/xfce4/terminal/terminalrc + colorschemes

  --mousepad             mousepad installation

  --mc                   midnight commander installation with vim hotkeys

  --tmux                 terminal multiplexer installation

  --vim                  vim installation with plugins

  --vifm                 vifm installation

  --gdb                  gdb debugger installation

  --local-bin            ~/.local/bin installation

  --local-share          ~/.local/share installation

  --gitconfig            ~/.gitconfig installation

  --unclutter            unclutter installation

  --newsboat             rss feed reader installation

  --neomutt              neomutt installation (mail reader)

  --telegram-desktop     telegram desktop installation autostart

  --firefox              install firefox clean profiles with custom user.js

  --games                game scripts installation (diablo1, diablo2, heroes3, quake1, quake2, quake3)

  --lightdm              lightdm installation
                         /etc/lightdm/lightdm-gtk-greeter.conf

  --ssh-server           ssh server installation
                         /etc/ssh/sshd_config

  --qa-debian-service    install systemd service for running QA Debian tools at startup

  --system-defaults      install system default configs

  --docker               install new docker packages

  --set-korux-theme      set korux-theme for desktop-base + remove warnings from icons

  -h, --help             show this help and exit

EOF

exit 0
}

# ----------------------------------------------------------------------

for arg in "$@"; do
	case "$arg" in
		"--install-packages")
			bold_message "Install environment packages from pkgs.list"
			if check_package eatmydata; then
				set +e
				for p in $(grep -v '^#' pkgs.list); do
					if ! check_package $p; then
						sudo eatmydata apt-get -y install $p
						echo -e "$?\n"
					fi
				done
				set -e
			else
				>&2 echo "Please, install 'eatmydata' package"
				exit 1
			fi

			sudo mandb
			sudo apt-file update
		;;

		"--purge-packages")
			bold_message "Free the system from unnecessary packages"
			sudo apt-get purge -y mlterm* xiterm+thai mozc* anthy* goldendict \
			quodlibet exfalso im-config ibus mythes* myspell* hyphen* \
			hunspell* aspell* libreoffice-l10n* firefox-esr-l10n* \
			debian-reference-es debian-reference-it fortunes-debian-hints fortune-mod \
			fcitx5 goldendict-ng xsane

			sudo apt-get autoremove -y
			sudo apt-get autoclean

			# These packages get removed as dependencies
			# unintentionally, so I reinstall them.
			sudo apt-get install dconf-cli keyutils

			dpkg -l | awk '/^rc/{print $2}' | xargs sudo apt-get purge -y

			sudo apt-file update
			sudo mandb
		;;

		"--sources-list")
			bold_message "sources.list installation (Trixie)"
			sudo cp -v ./sources.list /etc/apt/
			sudo apt-get update
		;;

		"--clean-home")
			bold_message "Cleanup $HOME"

			trash_dirs=(Видео Общедоступные Шаблоны Документы \
			            Videos Public Templates Documents)

			# I don't need these dirs =)
			for dir in ${trash_dirs[*]}; do
				[ -d ~/$dir ] && rm -ri ~/$dir
			done

			mkdir ~/git &>/dev/null | true
			mkdir ~/sources &>/dev/null | true
			ls ~

			cp -v ./.config/user-dirs.dirs ~/.config
			cp -v ./.config/user-dirs.locale ~/.config

			sudo cp ./root/etc/init.d/clean-home /etc/init.d
			sudo chmod 755 /etc/init.d/clean-home

			# Enable clean-home in startup.
			sudo update-rc.d clean-home defaults
		;;

		"--bash")
			bold_message "Bash installation"
			cp -v ./.bashrc ~/
			cp -v ./.bash_aliases ~/
			mkdir -p ~/.config/fastfetch &>/dev/null | true
			cp -v ./.config/fastfetch/config.jsonc ~/.config/fastfetch
		;;

		"--dircolors")
			bold_message "dircolors installation"
			cp -v ./.dircolors ~/
		;;

		"--bash-completion")
			bold_message "Enable bash completion"
			if check_package bash-completion; then
				sudo perl -i -pe '$i++ if /^#if ! shopt -oq posix;/; s/^#// if $i==1; $i=0 if /^fi/' \
				/etc/bash.bashrc
			else
				>&2 echo "Please, install 'bash-completion' package"
				exit 1
			fi
		;;

		"--sudo")
			bold_message "Add a $USER to the sudo group"
			if ! groups $USER | grep -q '\<sudo\>'; then
				sudo usermod -aG sudo $USER
			fi
			# I also like to use this configuration, but be aware
			# that it is not safe:
			# $ sudo visudo
			# user <TAB> ALL=(ALL:ALL) NOPASSWD:ALL
		;;

		"--locales")
			bold_message "Generate locales"
			if check_package locales; then
				for loc in en_US.UTF-8 ru_RU.UTF-8; do
					if ! grep ^$loc /etc/locale.gen &>/dev/null; then
						echo "$loc UTF-8" | sudo tee -a /etc/locale.gen
						sudo locale-gen
					fi
				done

				echo LANG="en_US.UTF-8" | sudo tee /etc/default/locale
			else
				>&2 echo "Please, install 'locales' package"
				exit 1
			fi
		;;

		"--xfce")
			bold_message "XFCE installation"
			if [ -n $XDG_CURRENT_DESKTOP ] && [ $XDG_CURRENT_DESKTOP == "XFCE" ]; then
				cp -v ./.config/xfce4/xfconf/xfce-perchannel-xml/* \
				~/.config/xfce4/xfconf/xfce-perchannel-xml
				cp -v ./.config/xfce4/helpers.rc ~/.config/xfce4
			else
				>&2 echo "Current desktop environment not 'XFCE'"
				exit 1
			fi

			# Max brightness for laptops.
			device_name=$(find /sys/class/backlight/ -mindepth 1)
			if [ -n "$device_name" ]; then
				max_brightness=$(cat $device_name/max_brightness)
				echo $max_brightness | sudo tee $device_name/brightness
			fi

			# Delete unattractive default backgrounds.
			# Look at these ~/.local/share/backgrounds/
			[ -d /usr/share/backgrounds/xfce/ ] && \
			sudo rm /usr/share/backgrounds/xfce/* &>/dev/null

			# Install fonts.
			mkdir ~/.fonts &>/dev/null | true
			cp -v ./root/usr/share/fonts/truetype/pxplus-cordata/* ~/.fonts
			fc-cache -f
		;;

		"--xfce-terminal")
			bold_message "XFCE terminal emulator installation"
			if check_package xfce4-terminal; then
				mkdir ~/.config/xfce4/terminal &>/dev/null | true
				cp -v ./.config/xfce4/terminal/terminalrc ~/.config/xfce4/terminal
				cp -v ./.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-terminal.xml \
				~/.config/xfce4/xfconf/xfce-perchannel-xml

				mkdir -p ~/.local/share/xfce4/terminal/colorschemes &>/dev/null | true
				cp -v ./.local/share/xfce4/terminal/colorschemes/* \
				~/.local/share/xfce4/terminal/colorschemes

				# Delete unattractive default color schemes.
				# Look at these ~/.local/share/xfce4/terminal/colorschemes/
				[ -d /usr/share/xfce4/terminal/colorschemes/ ] && \
				sudo rm -f /usr/share/xfce4/terminal/colorschemes/* &>/dev/null
			else
				>&2 echo "Please, install 'xfce4-terminal' package"
				exit 1
			fi
		;;

		"--mousepad")
			bold_message "Mousepad installation"
			if check_package mousepad; then
				# How export mousepad configuration? Commands:
				# $ dconf dump /org/xfce/mousepad/ > mousepad.settings
				# $ dconf load /org/xfce/mousepad/ < mousepad.settings
				cp -v ./.config/dconf/mousepad.settings ~/.config/dconf
				dconf load /org/xfce/mousepad/ < ~/.config/dconf/mousepad.settings
			else
				>&2 echo "Please, install 'mousepad' package"
				exit 1
			fi
		;;

		"--mc")
			bold_message "Midnight Commander installation with Vim hotkeys"
			if check_package mc; then
				mkdir -p ~/.config/mc &>/dev/null | true
				sudo mkdir -p /root/.config/mc &>/dev/null | true

				cp -v ./.config/mc/{ini,panels.ini,hotlist} ~/.config/mc
				sudo cp -v ./.config/mc/{ini,panels.ini} /root/.config/mc

				# Available with mc 4.8.33
				# https://github.com/MidnightCommander/mc/issues/4588
				if [ -e /etc/mc/mc.vim.keymap ]; then
					sudo rm /etc/mc/mc.keymap
					sudo ln -s /etc/mc/mc.vim.keymap /etc/mc/mc.keymap
				fi
			else
				>&2 echo "Please, install 'mc' package"
				exit 1
			fi
		;;

		"--tmux")
			bold_message "Tmux installation"
			if check_package tmux; then
				cp -v ./.tmux.conf ~/.tmux.conf
			else
				>&2 echo "Please, install 'tmux' package"
				exit 1
			fi
		;;

		"--vim")
			bold_message "Vim installation with plugins"
			if check_package vim; then
				plug_vim=~/.vim/autoload/plug.vim

				if [ ! -e $plug_vim ]; then
					curl -fLo $plug_vim --create-dirs \
					https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
				fi

				cp -v ./.vimrc ~/.vimrc
				vim +PlugClean +PlugInstall +q +q
			else
				>&2 echo "Please, install 'vim' package"
				exit 1
			fi
		;;

		"--vifm")
			bold_message "Vifm installation"
			if check_package vifm; then
				mkdir ~/.config/vifm &>/dev/null | true
				sudo mkdir -p /root/.config/vifm &>/dev/null | true
				cp -v ./.config/vifm/vifmrc ~/.config/vifm/vifmrc
				sudo cp -v ./.config/vifm/vifmrc /root/.config/vifm/vifmrc
			else
				>&2 echo "Please, install 'vifm' package"
				exit 1
			fi
		;;

		"--gdb")
			bold_message "GDB debugger installation"
			if check_package gdb; then
				if [ ! -e ~/.gdbinit ]; then
					wget -P ~/ https://git.io/.gdbinit
					check_package python3-pygments
				fi

				if grep -q "^# ----" ~/.gdbinit; then
					awk '/^# ----/{exit} {print}' ~/.gdbinit > ~/.gdbinit.new
					mv ~/.gdbinit.new ~/.gdbinit
				fi

				echo -e "\n# ----\n" >> ~/.gdbinit
				cat ./.gdbinit >> ~/.gdbinit
				echo -e "\n# ---- Don't write after this" >> ~/.gdbinit
			else
				>&2 echo "Please, install 'gdb' package"
				exit 1
			fi
		;;

		"--local-bin")
			bold_message "~/.local/bin installation"
			mkdir ~/.local/bin &>/dev/null | true
			cp -v ./.local/bin/* ~/.local/bin
		;;

		"--local-share")
			bold_message "~/.local/share installation"
			mkdir ~/.local/share &>/dev/null | true
			rsync -av --no-perms --exclude 'applications' ./.local/share/ ~/.local/share/
		;;

		"--gitconfig")
			bold_message "~/.gitconfig installation"
			if check_package git; then
				cp -v ./.gitconfig ~/
			else
				>&2 echo "Please, install 'git' package"
				exit 1
			fi
		;;

		"--unclutter")
			bold_message "Unclutter installation"
			if check_package unclutter && check_package unclutter-startup; then
				sudo sed -i 's/-idle 1/-idle 4/' /etc/default/unclutter
			else
				>&2 echo "Please, install 'unclutter' package"
				>&2 echo "Please, install 'unclutter-startup' package"
				exit 1
			fi
		;;

		"--newsboat")
			bold_message "RSS feed reader installation"
			if check_package newsboat; then
				mkdir ~/.newsboat &>/dev/null | true
				cp -v ./.newsboat/* ~/.newsboat
			else
				>&2 echo "Please, install 'newsboat' package"
				exit 1
			fi
		;;

		"--neomutt")
			bold_message "NeoMutt installation (mail reader)"
			if check_package neomutt; then
				cp -v ./.neomuttrc ~/
				cp -v ./.signature ~/
			else
				>&2 echo "Please, install 'neomutt' package"
				exit 1
			fi
		;;

		"--telegram-desktop")
			bold_message "Telegram Desktop installation autostart"
			if check_package telegram-desktop; then
				mkdir ~/.config/autostart &>/dev/null | true
				cp -v ./.config/autostart/org.telegram.desktop.desktop ~/.config/autostart
			else
				>&2 echo "Please, install 'telegram-desktop' package"
				exit 1
			fi
		;;

		"--firefox")
			bold_message "Install Firefox clean profiles with custom user.js"
			if check_package firefox-esr; then
				cp -vr ./.mozilla ~/
			else
				>&2 echo "Please, install 'firefox-esr' package"
				exit 1
			fi
		;;

		"--games")
			bold_message "Game scripts installation (diablo1, diablo2, heroes3, quake1, quake2, quake3)"
			if check_package game-data-packager && check_package play.it; then
				cp -v ./Free-Games ~/
				mkdir ~/.local/share/applications &>/dev/null | true
				cp -v ./.local/share/applications/* ~/.local/share/applications
				sudo cp -vr ./root/opt/game-scripts/ /opt
				sudo chown -R $USER: /opt/game-scripts
			else
				>&2 echo "Please, install 'game-data-packager' package"
				>&2 echo "Please, install 'play.it' package"
				exit 1
			fi
		;;

		"--lightdm")
			bold_message "LightDM installation"
			if check_package lightdm-gtk-greeter; then
				sudo cp -v ./root/etc/lightdm/lightdm-gtk-greeter.conf /etc/lightdm
				sudo chmod 644 /etc/lightdm/lightdm-gtk-greeter.conf
			else
				>&2 echo "Please, install 'lightdm-gtk-greeter' package"
				exit 1
			fi
		;;

		"--ssh-server")
			bold_message "SSH server installation"
			if check_package openssh-server; then
				sudo cp -v ./root/etc/ssh/sshd_config /etc/ssh
				sudo chmod 644 /etc/ssh/sshd_config
				sudo systemctl restart sshd.service
			else
				>&2 echo "Please, install 'openssh-server' package"
				exit 1
			fi
		;;

		"--qa-debian-service")
			bold_message "Install systemd service for running QA Debian tools at startup"
			# Service runs a script creating files in the home directory
			# at system startup. Files contain output from QA tools
			# such as 'how-can-i-help', useful for helping Debian.
			sudo cp -v ./root/etc/systemd/system/qa.service /etc/systemd/system
			sudo cp -v ./root/usr/local/bin/qa-at-boot /usr/local/bin
			sudo chmod 644 /etc/systemd/system/qa.service
			sudo chmod 755 /usr/local/bin/qa-at-boot
			sudo systemctl daemon-reload
			sudo systemctl enable qa.service
			sudo systemctl start qa.service
		;;

		"--system-defaults")
			bold_message "Install system default configs"
			sudo cp -v ./root/etc/default/{console-setup,grub,locale} /etc/default
			sudo chmod 644 /etc/default/{console-setup,grub,locale}
			sudo update-grub
		;;

		"--docker")
			bold_message "Install new docker packages"

			# Add Docker's official GPG key:
			sudo install -m 755 -d /etc/apt/keyrings
			sudo curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
			sudo chmod a+r /etc/apt/keyrings/docker.asc

			# Add the repository to Apt sources:
			echo \
			"deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] \
			https://download.docker.com/linux/debian trixie stable" | \
			sudo tee /etc/apt/sources.list.d/docker.list >/dev/null
			sudo chmod 644 /etc/apt/sources.list.d/docker.list

			sudo apt-get update
			sudo apt-get install -y \
					docker-ce \
					docker-ce-cli \
					containerd.io \
					docker-buildx-plugin \
					docker-compose-plugin
		;;

		"--set-korux-theme")
			bold_message "Set korux-theme for desktop-base"
			sudo cp -vr ./root/usr/share/desktop-base/korux-theme/ /usr/share/desktop-base
			sudo find /usr/share/desktop-base/korux-theme -type d -exec chmod 755 {} +
			sudo find /usr/share/desktop-base/korux-theme -type f -exec chmod 644 {} +
			sudo update-alternatives --install /usr/share/desktop-base/active-theme \
			desktop-theme /usr/share/desktop-base/korux-theme 50
			sudo update-alternatives --set desktop-theme /usr/share/desktop-base/korux-theme
			# Remove warnings from:
			# Settings -> Appearance -> Icons
			sudo update-icon-caches /usr/share/icons/*
		;;

		"-h" | "--help") usage ;;
	esac
done
